services:
  - type: web
    name: sports-image-classifier
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn sports_classifier.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
